/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherTimetableRouteImport } from './routes/teacher.timetable'
import { Route as TeacherLiveClassesRouteImport } from './routes/teacher.live-classes'
import { Route as TeacherExaminationsRouteImport } from './routes/teacher.examinations'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherCurriculumRouteImport } from './routes/teacher.curriculum'
import { Route as TeacherCoursesRouteImport } from './routes/teacher.courses'
import { Route as TeacherContentRouteImport } from './routes/teacher.content'
import { Route as TeacherAssessmentsRouteImport } from './routes/teacher.assessments'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentLiveClassesRouteImport } from './routes/student.live-classes'
import { Route as StudentHallTicketRouteImport } from './routes/student.hall-ticket'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCurriculumRouteImport } from './routes/student.curriculum'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentAssessmentsRouteImport } from './routes/student.assessments'
import { Route as StaffTasksRouteImport } from './routes/staff.tasks'
import { Route as StaffStudentsRouteImport } from './routes/staff.students'
import { Route as StaffRecordsRouteImport } from './routes/staff.records'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as StaffAnnouncementsRouteImport } from './routes/staff.announcements'
import { Route as AiProctoringRouteImport } from './routes/ai.proctoring'
import { Route as AiMeetingRouteImport } from './routes/ai.meeting'
import { Route as AiInterviewRouteImport } from './routes/ai.interview'
import { Route as AiFeedbackRouteImport } from './routes/ai.feedback'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminFacultyAssignmentRouteImport } from './routes/admin.faculty-assignment'
import { Route as AdminExaminationsRouteImport } from './routes/admin.examinations'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCurriculumRouteImport } from './routes/admin.curriculum'
import { Route as AdminContentReviewRouteImport } from './routes/admin.content-review'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as TeacherCoursesIndexRouteImport } from './routes/teacher.courses.index'
import { Route as StudentCoursesIndexRouteImport } from './routes/student.courses.index'
import { Route as TeacherCoursesCourseIdRouteImport } from './routes/teacher.courses.$courseId'
import { Route as StudentQuizQuizIdRouteImport } from './routes/student.quiz.$quizId'
import { Route as StudentCoursesCourseIdRouteImport } from './routes/student.courses.$courseId'
import { Route as AdminStudentsStudentIdRouteImport } from './routes/admin.students.$studentId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTimetableRoute = TeacherTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLiveClassesRoute = TeacherLiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExaminationsRoute = TeacherExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCurriculumRoute = TeacherCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherContentRoute = TeacherContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssessmentsRoute = TeacherAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLiveClassesRoute = StudentLiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHallTicketRoute = StudentHallTicketRouteImport.update({
  id: '/hall-ticket',
  path: '/hall-ticket',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCurriculumRoute = StudentCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssessmentsRoute = StudentAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => StudentRoute,
} as any)
const StaffTasksRoute = StaffTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStudentsRoute = StaffStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRecordsRoute = StaffRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAnnouncementsRoute = StaffAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => StaffRoute,
} as any)
const AiProctoringRoute = AiProctoringRouteImport.update({
  id: '/proctoring',
  path: '/proctoring',
  getParentRoute: () => AiRoute,
} as any)
const AiMeetingRoute = AiMeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => AiRoute,
} as any)
const AiInterviewRoute = AiInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AiRoute,
} as any)
const AiFeedbackRoute = AiFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AiRoute,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultyAssignmentRoute = AdminFacultyAssignmentRouteImport.update({
  id: '/faculty-assignment',
  path: '/faculty-assignment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExaminationsRoute = AdminExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurriculumRoute = AdminCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentReviewRoute = AdminContentReviewRouteImport.update({
  id: '/content-review',
  path: '/content-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherCoursesIndexRoute = TeacherCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherCoursesRoute,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentCoursesRoute,
} as any)
const TeacherCoursesCourseIdRoute = TeacherCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => TeacherCoursesRoute,
} as any)
const StudentQuizQuizIdRoute = StudentQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesCourseIdRoute = StudentCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => StudentCoursesRoute,
} as any)
const AdminStudentsStudentIdRoute = AdminStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AdminStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/apply': typeof ApplyRoute
  '/staff': typeof StaffRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/content-review': typeof AdminContentReviewRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/examinations': typeof AdminExaminationsRoute
  '/admin/faculty-assignment': typeof AdminFacultyAssignmentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/timetable': typeof AdminTimetableRoute
  '/ai/feedback': typeof AiFeedbackRoute
  '/ai/interview': typeof AiInterviewRoute
  '/ai/meeting': typeof AiMeetingRoute
  '/ai/proctoring': typeof AiProctoringRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/records': typeof StaffRecordsRoute
  '/staff/students': typeof StaffStudentsRoute
  '/staff/tasks': typeof StaffTasksRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/hall-ticket': typeof StudentHallTicketRoute
  '/student/live-classes': typeof StudentLiveClassesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/content': typeof TeacherContentRoute
  '/teacher/courses': typeof TeacherCoursesRouteWithChildren
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/examinations': typeof TeacherExaminationsRoute
  '/teacher/live-classes': typeof TeacherLiveClassesRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/quiz/$quizId': typeof StudentQuizQuizIdRoute
  '/teacher/courses/$courseId': typeof TeacherCoursesCourseIdRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/teacher/courses/': typeof TeacherCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/apply': typeof ApplyRoute
  '/staff': typeof StaffRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/content-review': typeof AdminContentReviewRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/examinations': typeof AdminExaminationsRoute
  '/admin/faculty-assignment': typeof AdminFacultyAssignmentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/timetable': typeof AdminTimetableRoute
  '/ai/feedback': typeof AiFeedbackRoute
  '/ai/interview': typeof AiInterviewRoute
  '/ai/meeting': typeof AiMeetingRoute
  '/ai/proctoring': typeof AiProctoringRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/records': typeof StaffRecordsRoute
  '/staff/students': typeof StaffStudentsRoute
  '/staff/tasks': typeof StaffTasksRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/hall-ticket': typeof StudentHallTicketRoute
  '/student/live-classes': typeof StudentLiveClassesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/content': typeof TeacherContentRoute
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/examinations': typeof TeacherExaminationsRoute
  '/teacher/live-classes': typeof TeacherLiveClassesRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/quiz/$quizId': typeof StudentQuizQuizIdRoute
  '/teacher/courses/$courseId': typeof TeacherCoursesCourseIdRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/teacher/courses': typeof TeacherCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/apply': typeof ApplyRoute
  '/staff': typeof StaffRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/content-review': typeof AdminContentReviewRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/examinations': typeof AdminExaminationsRoute
  '/admin/faculty-assignment': typeof AdminFacultyAssignmentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/timetable': typeof AdminTimetableRoute
  '/ai/feedback': typeof AiFeedbackRoute
  '/ai/interview': typeof AiInterviewRoute
  '/ai/meeting': typeof AiMeetingRoute
  '/ai/proctoring': typeof AiProctoringRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/records': typeof StaffRecordsRoute
  '/staff/students': typeof StaffStudentsRoute
  '/staff/tasks': typeof StaffTasksRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/hall-ticket': typeof StudentHallTicketRoute
  '/student/live-classes': typeof StudentLiveClassesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/content': typeof TeacherContentRoute
  '/teacher/courses': typeof TeacherCoursesRouteWithChildren
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/examinations': typeof TeacherExaminationsRoute
  '/teacher/live-classes': typeof TeacherLiveClassesRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/quiz/$quizId': typeof StudentQuizQuizIdRoute
  '/teacher/courses/$courseId': typeof TeacherCoursesCourseIdRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/teacher/courses/': typeof TeacherCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/apply'
    | '/staff'
    | '/student'
    | '/teacher'
    | '/admin/admissions'
    | '/admin/content-review'
    | '/admin/curriculum'
    | '/admin/dashboard'
    | '/admin/examinations'
    | '/admin/faculty-assignment'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/timetable'
    | '/ai/feedback'
    | '/ai/interview'
    | '/ai/meeting'
    | '/ai/proctoring'
    | '/staff/announcements'
    | '/staff/dashboard'
    | '/staff/records'
    | '/staff/students'
    | '/staff/tasks'
    | '/student/assessments'
    | '/student/courses'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/fees'
    | '/student/hall-ticket'
    | '/student/live-classes'
    | '/student/profile'
    | '/student/timetable'
    | '/teacher/assessments'
    | '/teacher/content'
    | '/teacher/courses'
    | '/teacher/curriculum'
    | '/teacher/dashboard'
    | '/teacher/examinations'
    | '/teacher/live-classes'
    | '/teacher/timetable'
    | '/admin/students/$studentId'
    | '/student/courses/$courseId'
    | '/student/quiz/$quizId'
    | '/teacher/courses/$courseId'
    | '/student/courses/'
    | '/teacher/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai'
    | '/apply'
    | '/staff'
    | '/student'
    | '/teacher'
    | '/admin/admissions'
    | '/admin/content-review'
    | '/admin/curriculum'
    | '/admin/dashboard'
    | '/admin/examinations'
    | '/admin/faculty-assignment'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/timetable'
    | '/ai/feedback'
    | '/ai/interview'
    | '/ai/meeting'
    | '/ai/proctoring'
    | '/staff/announcements'
    | '/staff/dashboard'
    | '/staff/records'
    | '/staff/students'
    | '/staff/tasks'
    | '/student/assessments'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/fees'
    | '/student/hall-ticket'
    | '/student/live-classes'
    | '/student/profile'
    | '/student/timetable'
    | '/teacher/assessments'
    | '/teacher/content'
    | '/teacher/curriculum'
    | '/teacher/dashboard'
    | '/teacher/examinations'
    | '/teacher/live-classes'
    | '/teacher/timetable'
    | '/admin/students/$studentId'
    | '/student/courses/$courseId'
    | '/student/quiz/$quizId'
    | '/teacher/courses/$courseId'
    | '/student/courses'
    | '/teacher/courses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/apply'
    | '/staff'
    | '/student'
    | '/teacher'
    | '/admin/admissions'
    | '/admin/content-review'
    | '/admin/curriculum'
    | '/admin/dashboard'
    | '/admin/examinations'
    | '/admin/faculty-assignment'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/timetable'
    | '/ai/feedback'
    | '/ai/interview'
    | '/ai/meeting'
    | '/ai/proctoring'
    | '/staff/announcements'
    | '/staff/dashboard'
    | '/staff/records'
    | '/staff/students'
    | '/staff/tasks'
    | '/student/assessments'
    | '/student/courses'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/fees'
    | '/student/hall-ticket'
    | '/student/live-classes'
    | '/student/profile'
    | '/student/timetable'
    | '/teacher/assessments'
    | '/teacher/content'
    | '/teacher/courses'
    | '/teacher/curriculum'
    | '/teacher/dashboard'
    | '/teacher/examinations'
    | '/teacher/live-classes'
    | '/teacher/timetable'
    | '/admin/students/$studentId'
    | '/student/courses/$courseId'
    | '/student/quiz/$quizId'
    | '/teacher/courses/$courseId'
    | '/student/courses/'
    | '/teacher/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  StaffRoute: typeof StaffRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/timetable': {
      id: '/teacher/timetable'
      path: '/timetable'
      fullPath: '/teacher/timetable'
      preLoaderRoute: typeof TeacherTimetableRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/live-classes': {
      id: '/teacher/live-classes'
      path: '/live-classes'
      fullPath: '/teacher/live-classes'
      preLoaderRoute: typeof TeacherLiveClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/examinations': {
      id: '/teacher/examinations'
      path: '/examinations'
      fullPath: '/teacher/examinations'
      preLoaderRoute: typeof TeacherExaminationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/curriculum': {
      id: '/teacher/curriculum'
      path: '/curriculum'
      fullPath: '/teacher/curriculum'
      preLoaderRoute: typeof TeacherCurriculumRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/content': {
      id: '/teacher/content'
      path: '/content'
      fullPath: '/teacher/content'
      preLoaderRoute: typeof TeacherContentRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assessments': {
      id: '/teacher/assessments'
      path: '/assessments'
      fullPath: '/teacher/assessments'
      preLoaderRoute: typeof TeacherAssessmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/live-classes': {
      id: '/student/live-classes'
      path: '/live-classes'
      fullPath: '/student/live-classes'
      preLoaderRoute: typeof StudentLiveClassesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/hall-ticket': {
      id: '/student/hall-ticket'
      path: '/hall-ticket'
      fullPath: '/student/hall-ticket'
      preLoaderRoute: typeof StudentHallTicketRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/curriculum': {
      id: '/student/curriculum'
      path: '/curriculum'
      fullPath: '/student/curriculum'
      preLoaderRoute: typeof StudentCurriculumRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assessments': {
      id: '/student/assessments'
      path: '/assessments'
      fullPath: '/student/assessments'
      preLoaderRoute: typeof StudentAssessmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/staff/tasks': {
      id: '/staff/tasks'
      path: '/tasks'
      fullPath: '/staff/tasks'
      preLoaderRoute: typeof StaffTasksRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/students': {
      id: '/staff/students'
      path: '/students'
      fullPath: '/staff/students'
      preLoaderRoute: typeof StaffStudentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/records': {
      id: '/staff/records'
      path: '/records'
      fullPath: '/staff/records'
      preLoaderRoute: typeof StaffRecordsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/announcements': {
      id: '/staff/announcements'
      path: '/announcements'
      fullPath: '/staff/announcements'
      preLoaderRoute: typeof StaffAnnouncementsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/ai/proctoring': {
      id: '/ai/proctoring'
      path: '/proctoring'
      fullPath: '/ai/proctoring'
      preLoaderRoute: typeof AiProctoringRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/meeting': {
      id: '/ai/meeting'
      path: '/meeting'
      fullPath: '/ai/meeting'
      preLoaderRoute: typeof AiMeetingRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/interview': {
      id: '/ai/interview'
      path: '/interview'
      fullPath: '/ai/interview'
      preLoaderRoute: typeof AiInterviewRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/feedback': {
      id: '/ai/feedback'
      path: '/feedback'
      fullPath: '/ai/feedback'
      preLoaderRoute: typeof AiFeedbackRouteImport
      parentRoute: typeof AiRoute
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faculty-assignment': {
      id: '/admin/faculty-assignment'
      path: '/faculty-assignment'
      fullPath: '/admin/faculty-assignment'
      preLoaderRoute: typeof AdminFacultyAssignmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/examinations': {
      id: '/admin/examinations'
      path: '/examinations'
      fullPath: '/admin/examinations'
      preLoaderRoute: typeof AdminExaminationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/curriculum': {
      id: '/admin/curriculum'
      path: '/curriculum'
      fullPath: '/admin/curriculum'
      preLoaderRoute: typeof AdminCurriculumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-review': {
      id: '/admin/content-review'
      path: '/content-review'
      fullPath: '/admin/content-review'
      preLoaderRoute: typeof AdminContentReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/courses/': {
      id: '/teacher/courses/'
      path: '/'
      fullPath: '/teacher/courses/'
      preLoaderRoute: typeof TeacherCoursesIndexRouteImport
      parentRoute: typeof TeacherCoursesRoute
    }
    '/student/courses/': {
      id: '/student/courses/'
      path: '/'
      fullPath: '/student/courses/'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
    '/teacher/courses/$courseId': {
      id: '/teacher/courses/$courseId'
      path: '/$courseId'
      fullPath: '/teacher/courses/$courseId'
      preLoaderRoute: typeof TeacherCoursesCourseIdRouteImport
      parentRoute: typeof TeacherCoursesRoute
    }
    '/student/quiz/$quizId': {
      id: '/student/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/student/quiz/$quizId'
      preLoaderRoute: typeof StudentQuizQuizIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses/$courseId': {
      id: '/student/courses/$courseId'
      path: '/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof StudentCoursesCourseIdRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
    '/admin/students/$studentId': {
      id: '/admin/students/$studentId'
      path: '/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdRouteImport
      parentRoute: typeof AdminStudentsRoute
    }
  }
}

interface AdminStudentsRouteChildren {
  AdminStudentsStudentIdRoute: typeof AdminStudentsStudentIdRoute
}

const AdminStudentsRouteChildren: AdminStudentsRouteChildren = {
  AdminStudentsStudentIdRoute: AdminStudentsStudentIdRoute,
}

const AdminStudentsRouteWithChildren = AdminStudentsRoute._addFileChildren(
  AdminStudentsRouteChildren,
)

interface AdminRouteChildren {
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminContentReviewRoute: typeof AdminContentReviewRoute
  AdminCurriculumRoute: typeof AdminCurriculumRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExaminationsRoute: typeof AdminExaminationsRoute
  AdminFacultyAssignmentRoute: typeof AdminFacultyAssignmentRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRouteWithChildren
  AdminTimetableRoute: typeof AdminTimetableRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminContentReviewRoute: AdminContentReviewRoute,
  AdminCurriculumRoute: AdminCurriculumRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExaminationsRoute: AdminExaminationsRoute,
  AdminFacultyAssignmentRoute: AdminFacultyAssignmentRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStudentsRoute: AdminStudentsRouteWithChildren,
  AdminTimetableRoute: AdminTimetableRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AiRouteChildren {
  AiFeedbackRoute: typeof AiFeedbackRoute
  AiInterviewRoute: typeof AiInterviewRoute
  AiMeetingRoute: typeof AiMeetingRoute
  AiProctoringRoute: typeof AiProctoringRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiFeedbackRoute: AiFeedbackRoute,
  AiInterviewRoute: AiInterviewRoute,
  AiMeetingRoute: AiMeetingRoute,
  AiProctoringRoute: AiProctoringRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface StaffRouteChildren {
  StaffAnnouncementsRoute: typeof StaffAnnouncementsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffRecordsRoute: typeof StaffRecordsRoute
  StaffStudentsRoute: typeof StaffStudentsRoute
  StaffTasksRoute: typeof StaffTasksRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAnnouncementsRoute: StaffAnnouncementsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffRecordsRoute: StaffRecordsRoute,
  StaffStudentsRoute: StaffStudentsRoute,
  StaffTasksRoute: StaffTasksRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface StudentCoursesRouteChildren {
  StudentCoursesCourseIdRoute: typeof StudentCoursesCourseIdRoute
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
}

const StudentCoursesRouteChildren: StudentCoursesRouteChildren = {
  StudentCoursesCourseIdRoute: StudentCoursesCourseIdRoute,
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
}

const StudentCoursesRouteWithChildren = StudentCoursesRoute._addFileChildren(
  StudentCoursesRouteChildren,
)

interface StudentRouteChildren {
  StudentAssessmentsRoute: typeof StudentAssessmentsRoute
  StudentCoursesRoute: typeof StudentCoursesRouteWithChildren
  StudentCurriculumRoute: typeof StudentCurriculumRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentHallTicketRoute: typeof StudentHallTicketRoute
  StudentLiveClassesRoute: typeof StudentLiveClassesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  StudentQuizQuizIdRoute: typeof StudentQuizQuizIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssessmentsRoute: StudentAssessmentsRoute,
  StudentCoursesRoute: StudentCoursesRouteWithChildren,
  StudentCurriculumRoute: StudentCurriculumRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentHallTicketRoute: StudentHallTicketRoute,
  StudentLiveClassesRoute: StudentLiveClassesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  StudentQuizQuizIdRoute: StudentQuizQuizIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherCoursesRouteChildren {
  TeacherCoursesCourseIdRoute: typeof TeacherCoursesCourseIdRoute
  TeacherCoursesIndexRoute: typeof TeacherCoursesIndexRoute
}

const TeacherCoursesRouteChildren: TeacherCoursesRouteChildren = {
  TeacherCoursesCourseIdRoute: TeacherCoursesCourseIdRoute,
  TeacherCoursesIndexRoute: TeacherCoursesIndexRoute,
}

const TeacherCoursesRouteWithChildren = TeacherCoursesRoute._addFileChildren(
  TeacherCoursesRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAssessmentsRoute: typeof TeacherAssessmentsRoute
  TeacherContentRoute: typeof TeacherContentRoute
  TeacherCoursesRoute: typeof TeacherCoursesRouteWithChildren
  TeacherCurriculumRoute: typeof TeacherCurriculumRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherExaminationsRoute: typeof TeacherExaminationsRoute
  TeacherLiveClassesRoute: typeof TeacherLiveClassesRoute
  TeacherTimetableRoute: typeof TeacherTimetableRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAssessmentsRoute: TeacherAssessmentsRoute,
  TeacherContentRoute: TeacherContentRoute,
  TeacherCoursesRoute: TeacherCoursesRouteWithChildren,
  TeacherCurriculumRoute: TeacherCurriculumRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherExaminationsRoute: TeacherExaminationsRoute,
  TeacherLiveClassesRoute: TeacherLiveClassesRoute,
  TeacherTimetableRoute: TeacherTimetableRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRouteWithChildren,
  ApplyRoute: ApplyRoute,
  StaffRoute: StaffRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
